spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    password: 'postgres'
    username: postgres
    url: jdbc:postgresql://postgresqldb:5432/flights

