spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  datasource:
    password: 'postgres'
    username: postgres
    url: jdbc:postgresql://postgresqldb:5432/flights
  data:
    redis:
      host: redis
      port: 6379
      ttl: 60

api:
  flight:
    url: http://mock-flight-api:3000
    fetch:
      count: 20
      cron : 0 */3 * * * *
  contact:
    author:
      name: "Ikram Dagci"
      email: ikramdgc@gmail.com
      website: https://www.linkedin.com/in/ikramdagci/
  description: "manage flight-related information, including flights and airports, and perform flight searches."


logging:
  level:
    org.javamoney.moneta.Money: ERROR

