spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    password: 'postgres'
    username: postgres
    url: jdbc:postgresql://localhost:5432/flights
  data:
    jpa:
      repositories:
        query:
          enable-optimizations: false
    redis:
      host: localhost
      port: 6379

api:
  flight:
    url: http://localhost:3000
    fetch:
      count: 10

logging:
  level:
    org.javamoney.moneta.Money: ERROR

