spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  datasource:
    password: 'postgres'
    username: postgres
    url: jdbc:postgresql://postgresqldb:5432/flights

mock:
  flight:
    api:
      url: http://mock-flight-api:3000
      fetch:
        count: 50

logging:
  level:
    org.javamoney.moneta.Money: ERROR

