spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    password: 'postgres'
    username: postgres
    url: jdbc:postgresql://localhost:5432/flights
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 60

api:
  flight:
    url: http://localhost:3000
    fetch:
      count: 20
      cron : 0 */1 * * * *

logging:
  level:
    org.javamoney.moneta.Money: ERROR

